// <auto-generated />
namespace QTProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class customer_address : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(customer_address));
        
        string IMigrationMetadata.Id
        {
            get { return "202004051413313_customer_address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
